export const recipes = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    description: "Classic Italian pasta dish with bacon, eggs, and cheese.",
    prepTime: "15 minutes",
    cookTime: "15 minutes",
    mediaURL: "https://picsum.photos/500/500.webp",
    cuisineType: "Italian",
    ingredients: [
      "200g spaghetti",
      "150g bacon, diced",
      "2 eggs",
      "50g Parmesan cheese, grated",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook spaghetti according to package instructions. Drain and set aside.",
      "In a large skillet, cook bacon over medium heat until crispy. Remove from the skillet and drain excess fat.",
      "In a bowl, beat the eggs and mix in the grated Parmesan cheese. Season with salt and pepper.",
      "Add the cooked spaghetti to the skillet with the bacon. Pour the egg and cheese mixture over the spaghetti and quickly toss to coat. The heat from the spaghetti will cook the eggs, creating a creamy sauce.",
      "Serve immediately and garnish with additional grated Parmesan cheese.",
    ],
  },
  {
    id: 2,
    title: "Chicken Stir-Fry",
    description: "Quick and easy stir-fried chicken with vegetables.",
    prepTime: "10 minutes",
    cookTime: "15 minutes",
    mediaURL: "https://picsum.photos/500/500.webp",
    cuisineType: "Asian",
    ingredients: [
      "2 boneless, skinless chicken breasts, sliced",
      "1 bell pepper, sliced",
      "1 onion, sliced",
      "2 cloves of garlic, minced",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon sesame oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a large skillet or wok, heat the sesame oil over medium-high heat.",
      "Add the sliced chicken breasts and cook until browned and cooked through. Remove from the skillet and set aside.",
      "In the same skillet, add the sliced bell pepper and onion. Stir-fry for a few minutes until they start to soften.",
      "Add the minced garlic and stir-fry for another minute.",
      "Return the cooked chicken to the skillet. Add the soy sauce and oyster sauce. Stir-fry for a couple of minutes until everything is well coated and heated through.",
      "Season with salt and pepper to taste.",
      "Serve hot with steamed rice or noodles.",
    ],
  },
  {
    id: 3,
    title: "Beef Tacos",
    description: "Flavorful Mexican tacos with seasoned beef and toppings.",
    prepTime: "20 minutes",
    cookTime: "15 minutes",
    mediaURL: "https://picsum.photos/500/500.webp",
    cuisineType: "Mexican",
    ingredients: [
      "500g ground beef",
      "1 tablespoon olive oil",
      "1 onion, diced",
      "2 cloves of garlic, minced",
      "1 tablespoon chili powder",
      "1 teaspoon cumin",
      "1 teaspoon paprika",
      "Salt and pepper to taste",
      "8 small corn tortillas",
      "Toppings: shredded lettuce, diced tomatoes, grated cheese, salsa, sour cream",
    ],
    instructions: [
      "In a large skillet, heat olive oil over medium heat. Add the diced onion and minced garlic, and sauté until the onion is translucent.",
      "Add the ground beef to the skillet and cook until browned. Break it up with a spoon while cooking.",
      "Stir in the chili powder, cumin, paprika, salt, and pepper. Cook for a few more minutes to allow the flavors to meld.",
      "Warm the corn tortillas in a separate skillet or on a griddle.",
      "Assemble the tacos by spooning the beef mixture onto each tortilla. Top with shredded lettuce, diced tomatoes, grated cheese, salsa, and sour cream.",
      "Serve hot and enjoy!",
    ],
  },
  // {
  //   id: 4,
  //   title: "Mushroom Risotto",
  //   description: "Creamy Italian rice dish with mushrooms and Parmesan cheese.",
  //   prepTime: "10 minutes",
  //   cookTime: "25 minutes",
  //   mediaURL: "https://picsum.photos/500/500.webp",
  //   cuisineType: "Italian",
  //   ingredients: [
  //     "1 cup Arborio rice",
  //     "2 cups vegetable broth",
  //     "1 cup sliced mushrooms",
  //     "1 small onion, diced",
  //     "2 cloves of garlic, minced",
  //     "2 tablespoons butter",
  //     "1/4 cup grated Parmesan cheese",
  //     "Salt and pepper to taste",
  //     "Chopped fresh parsley for garnish",
  //   ],
  //   instructions: [
  //     "In a medium saucepan, heat the vegetable broth and keep it warm over low heat.",
  //     "In a separate large saucepan, melt the butter over medium heat. Add the diced onion and minced garlic, and sauté until the onion is translucent.",
  //     "Add the Arborio rice to the saucepan and stir to coat the rice with the butter. Cook for a couple of minutes until the rice becomes slightly toasted.",
  //     "Add a ladleful of warm vegetable broth to the rice and stir until the liquid is absorbed. Repeat this process, adding the broth gradually, until the rice is cooked al dente and creamy. This will take about 20-25 minutes.",
  //     "Stir in the sliced mushrooms and cook for a few more minutes until they are tender.",
  //     "Remove the risotto from heat and stir in the grated Parmesan cheese. Season with salt and pepper to taste.",
  //     "Garnish with chopped fresh parsley and serve hot.",
  //   ],
  // },
  // {
  //   id: 5,
  //   title: "Chicken Curry",
  //   description: "Flavorful Indian chicken curry with aromatic spices.",
  //   prepTime: "15 minutes",
  //   cookTime: "30 minutes",
  //   mediaURL: "https://picsum.photos/500/500.webp",
  //   cuisineType: "Indian",
  //   ingredients: [
  //     "500g boneless chicken, cut into pieces",
  //     "2 tablespoons vegetable oil",
  //     "1 onion, finely chopped",
  //     "2 cloves of garlic, minced",
  //     "1-inch piece of ginger, grated",
  //     "2 teaspoons curry powder",
  //     "1 teaspoon turmeric",
  //     "1 teaspoon cumin",
  //     "1 teaspoon coriander",
  //     "1 cup coconut milk",
  //     "1 cup chicken broth",
  //     "Salt and pepper to taste",
  //     "Fresh cilantro for garnish",
  //   ],
  //   instructions: [
  //     "In a large skillet, heat the vegetable oil over medium heat. Add the chopped onion and sauté until golden brown.",
  //     "Add the minced garlic and grated ginger to the skillet and sauté for another minute.",
  //     "Add the chicken pieces to the skillet and cook until they are browned on all sides.",
  //     "In a small bowl, mix together the curry powder, turmeric, cumin, and coriander with a splash of water to form a paste. Add the spice paste to the skillet and stir well to coat the chicken.",
  //     "Pour in the coconut milk and chicken broth. Season with salt and pepper to taste.",
  //     "Simmer the curry over low heat for about 20-25 minutes, or until the chicken is cooked through and tender.",
  //     "Garnish with fresh cilantro and serve hot with steamed rice or naan bread.",
  //   ],
  // },
];
